version: "3.7"
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  app:
    image: tilt.dev/express-redis-app
    container_name: application
    links:
      - redis
    ports:
      - 30002:30002
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=development
      - PORT=30002
    command:
      sh -c 'node server.js'